
quest:
  name: Give till' it hurts
  location: 
    - Goto: Right
    - Goto: Right
    - Goto: Right
    - Goto: 0.95, 0.3
    - Goto: Right
    - Goto: Right
    - Click: Robina sitting
    - Click: Talk
    - Click: Quests
    - Click: Give till it hurts
    - Click: 2
    - Click: Quest!

map:
    type: static
    heal: 
        - Click: 0.8, 0.3
        - Wait: 1
        - Click: 0.8, 0.3
    layout:
        - Goto: Left
        - Fight: Basilisk
        - Goto: Right
        - Goto: Up
        - Fight: Tigercorn, Clawkin Wanderer
        - Goto: Down
        - Goto: Right
        - Fight: Grass Bull, Clawkin Wanderer
        - Goto: Right

loop-heal:
    - Click: Heal
    - Click: Quests
    - Click: Give till it hurts
    - Click: 2
    - Click: Quest!

loop:
    - Click: Quests
    - Click: Give till it hurts
    - Click: 2
    - Click: Quest!
